# Generated by Django 5.0.7 on 2024-07-31 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WatchlistMovie",
        ),
    ]
