# Generated by Django 5.0.7 on 2024-08-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_delete_watchlistmovie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("min_movies_watched", models.IntegerField()),
            ],
        ),
    ]
