# Generated by Django 5.0.7 on 2024-08-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
