# Generated by Django 5.0.7 on 2024-08-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_level_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="description",
            field=models.TextField(default="Aucune description"),
        ),
    ]
